version: '3'

services:
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: username
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: example_db
#    ports:
#      - "5432:5432"
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_user_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
  my-app:
    build: ./
    command: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mysql