bind_addr = ":8080"
log_level = "debug"

[store]
#database_url = "user=username password=password dbname=example_db host=localhost port=5432 sslmode=disable"
database_url = "example_user:example_user_password@tcp(mysql:3306)/example_db"
#change localhost to mysql